version: '3.8'

services:
  insurai-backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: insurai-backend
    ports:
      - "9000:8080"
    dns:
      - 8.8.8.8
      - 8.8.4.4

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.txkgemcpojqaqzjyrfrr&password=FQuy0qTYMyY38tST
      SPRING_DATASOURCE_USERNAME: postgres.txkgemcpojqaqzjyrfrr
      SPRING_DATASOURCE_PASSWORD: FQuy0qTYMyY38tST
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      JAVA_TOOL_OPTIONS: "-Djava.net.preferIPv4Stack=true"

      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: 'false'

      SERVER_PORT: 8080
    restart: unless-stopped
